-- MySQL Script generated by MySQL Workbench
-- Sat Apr 15 21:48:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ECommPortal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ECommPortal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ECommPortal` DEFAULT CHARACTER SET utf8 ;
USE `ECommPortal` ;

-- -----------------------------------------------------
-- Table `ECommPortal`.`dim_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECommPortal`.`dim_customers` (
  `customer_id` INT NOT NULL,
  `customer_first_name` VARCHAR(45) NOT NULL,
  `customer_last_name` VARCHAR(45) NOT NULL,
  `customer_address` VARCHAR(100) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `city` VARCHAR(15) NOT NULL,
  `state` VARCHAR(10) NOT NULL,
  `country` VARCHAR(20) NOT NULL,
  `pincode` INT(6) NOT NULL,
  `customer_contact_number` INT(10) NOT NULL,
  `customer_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_email_UNIQUE` (`customer_email` ASC) VISIBLE,
  UNIQUE INDEX `customer_contact_number_UNIQUE` (`customer_contact_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommPortal`.`dim_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECommPortal`.`dim_products` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `product_type` VARCHAR(45) NOT NULL,
  `product_price` FLOAT NOT NULL,
  `dim_productscol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommPortal`.`dim_payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECommPortal`.`dim_payments` (
  `payment_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `payment_type` VARCHAR(45) NOT NULL,
  `credict_card_num` VARCHAR(45) NOT NULL,
  `expiry_date` DATE NOT NULL,
  `CVV` INT(3) NOT NULL,
  `email_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `customerID_FK1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customerID_FK1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `ECommPortal`.`dim_customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommPortal`.`fact_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECommPortal`.`fact_orders` (
  `order_id` INT NOT NULL,
  `device` VARCHAR(45) NULL,
  `product_id` INT NULL,
  `customer_id` INT NULL,
  `payment_id` INT NULL,
  `shipping_address` VARCHAR(45) NULL,
  `shipping_city` VARCHAR(45) NULL,
  `shipping_state` VARCHAR(45) NULL,
  `shipping_country` VARCHAR(45) NULL,
  `delivery_status` CHAR(1) NULL,
  PRIMARY KEY (`order_id`),
  INDEX `FK1_product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `FK2_cust_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `FK3_payment_id_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `FK1_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `ECommPortal`.`dim_products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK2_cust_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `ECommPortal`.`dim_customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK3_payment_id`
    FOREIGN KEY (`payment_id`)
    REFERENCES `ECommPortal`.`dim_payments` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
