-- MySQL Script generated by MySQL Workbench
-- Mon Apr 17 00:20:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema food_delivery_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food_delivery_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_delivery_app` DEFAULT CHARACTER SET utf8 ;
USE `food_delivery_app` ;

-- -----------------------------------------------------
-- Table `food_delivery_app`.`user_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_app`.`user_dim` (
  `user_id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`restaurant_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_app`.`restaurant_dim` (
  `restaurant_id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `latlong` POINT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `pincode` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`restaurant_id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`menu_item_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_app`.`menu_item_dim` (
  `item_id` VARCHAR(10) NOT NULL,
  `restaurant_id` VARCHAR(10) NOT NULL,
  `item_name` VARCHAR(45) NOT NULL,
  `item_price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `FK_restaurant_key_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `FK_restaurant_key`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `food_delivery_app`.`restaurant_dim` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`driver_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_app`.`driver_dim` (
  `driver_id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `current_latlong` POINT NOT NULL,
  `driver_licence_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`driver_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`payment_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_app`.`payment_dim` (
  `payment_id` VARCHAR(10) NOT NULL,
  `order_id` VARCHAR(10) NOT NULL,
  `mode_of_payment` VARCHAR(45) NOT NULL,
  `amount` DECIMAL(7,2) NOT NULL,
  `payment_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `FK_order_id_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FK_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `food_delivery_app`.`orders_fact` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`address_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_app`.`address_dim` (
  `address_id` VARCHAR(10) NOT NULL,
  `user_id` VARCHAR(10) NOT NULL,
  `latlong` POINT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `pincode` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `FK_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `food_delivery_app`.`user_dim` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`orders_fact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_app`.`orders_fact` (
  `order_id` VARCHAR(10) NOT NULL,
  `order_datetime` DATETIME NOT NULL,
  `user_id` VARCHAR(10) NOT NULL,
  `restaurant_id` VARCHAR(10) NOT NULL,
  `item_id` VARCHAR(10) NOT NULL,
  `driver_id` VARCHAR(10) NOT NULL,
  `delivery_address_id` VARCHAR(10) NOT NULL,
  `payment_id` VARCHAR(10) NOT NULL,
  `order_total` DECIMAL(7,2) NOT NULL,
  `order_rating` TINYINT UNSIGNED NOT NULL,
  `delivery_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `FK_userID_idx` (`user_id` ASC) VISIBLE,
  INDEX `FK_restaurant_id_idx` (`restaurant_id` ASC) VISIBLE,
  INDEX `FK_itemID_idx` (`item_id` ASC) VISIBLE,
  INDEX `FK_driver_id_idx` (`driver_id` ASC) VISIBLE,
  INDEX `FK_payment_id_idx` (`payment_id` ASC) VISIBLE,
  INDEX `FK_deliver_address_idx` (`delivery_address_id` ASC) VISIBLE,
  CONSTRAINT `FK_userID`
    FOREIGN KEY (`user_id`)
    REFERENCES `food_delivery_app`.`user_dim` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `food_delivery_app`.`restaurant_dim` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_itemID`
    FOREIGN KEY (`item_id`)
    REFERENCES `food_delivery_app`.`menu_item_dim` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_driver_id`
    FOREIGN KEY (`driver_id`)
    REFERENCES `food_delivery_app`.`driver_dim` (`driver_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_payment_id`
    FOREIGN KEY (`payment_id`)
    REFERENCES `food_delivery_app`.`payment_dim` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_deliver_address`
    FOREIGN KEY (`delivery_address_id`)
    REFERENCES `food_delivery_app`.`address_dim` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`restaurant_ratings_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_app`.`restaurant_ratings_dim` (
  `rating_id` VARCHAR(10) NOT NULL,
  `user_id` VARCHAR(10) NOT NULL,
  `restaurant_id` VARCHAR(10) NOT NULL,
  `restaurant_rating` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`rating_id`),
  INDEX `FK_restaurant_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `FK_restaurant`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `food_delivery_app`.`restaurant_dim` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
